### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [walczakw/prj-rev-bwfs-dasmoto#6]
It can be a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are a few shared properties that you can simplify by applying to multiple selectors at once, rather than individually. 

For instance, each selector has the same font-family, and each h2 element shares several properties. You might simplify it like so

```css
body {
  font-family: Helvetica;
}

h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
